version: '3.4'

services:
    mariadb:
        image: itkdev/mariadb:latest
        ports:
            - '3306'
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_USER=db
            - MYSQL_PASSWORD=db
            - MYSQL_DATABASE=db
            #- ENCRYPT=1 # Uncomment to enable database encryptionn.
        labels:
            com.symfony.server.service-prefix: 'DATABASE'

    phpfpm:
        image: itkdev/php7.4-fpm:latest
        environment:
            - PHP_XDEBUG=${PHP_XDEBUG:-0}
            - PHP_XDEBUG_REMOTE_AUTOSTART=${PHP_XDEBUG_REMOTE_AUTOSTART:-0}
            - PHP_XDEBUG_REMOTE_HOST=${PHP_XDEBUG_REMOTE_HOST:-0.0.0.0}
            - PHP_XDEBUG_REMOTE_CONNECT_BACK=${PHP_XDEBUG_REMOTE_CONNECT_BACK:-0}
            - PHP_MAX_EXECUTION_TIME=30
            - PHP_MEMORY_LIMIT=256M
            # - PHP_MAIL=1 # Uncomment to enable mailhog.
            - COMPOSER_VERSION=2
        depends_on:
            - mariadb
            - mercure
        volumes:
            - ./:/app:delegated
            # - .:/app:rw,cached
            # - /app/var/
            # - /app/var/cache/
            # - /app/var/logs/
            # - /app/var/sessions/

    nginx:
        image: nginx:latest
        depends_on:
            - phpfpm
        ports:
            - '8880:80'
        volumes:
            - ${PWD}/.docker/vhost.conf:/etc/nginx/conf.d/default.conf:ro
            - ./:/app:delegated
            # - ./public:/app/public:ro

    mailhog:
        image: mailhog/mailhog
        ports:
            - '1025'
            - '8825:8025'

    ###> symfony/mercure-bundle ###
    mercure:
        # In production, you may want to use the managed version of Mercure, https://mercure.rocks
        image: dunglas/mercure:v0.10.4
        environment:
            - JWT_KEY=!ChangeMe!
            - ALLOW_ANONYMOUS=1
            - CORS_ALLOWED_ORIGINS=*
            - PUBLISH_ALLOWED_ORIGINS=http://localhost:1337
            - DEMO=1

            # # You should definitely change all these values in production
            # - MERCURE_PUBLISHER_JWT_KEY='!ChangeMe!'
            # - MERCURE_SUBSCRIBER_JWT_KEY='!ChangeMe!'
            # # https://mercure.rocks/docs/hub/config#environment-variables
            # - MERCURE_EXTRA_DIRECTIVES='cors_origins *\ndemo'
            # # - ALLOW_ANONYMOUS=1
            # # - CORS_ALLOWED_ORIGINS='*'
            # # - PUBLISH_ALLOWED_ORIGINS=http://localhost:1337
            # - SERVER_NAME=http://0.0.0.0:8837
        ports:
            - '8837:80'
            # - "8838:443"
###< symfony/mercure-bundle ###
